# Generated by Django 3.2.15 on 2025-10-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('processamento', 'Em Processamento'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='processamento', max_length=20, verbose_name='Status'),
        ),
    ]
